### ISSUE TITLE
[EPIC] Package Management Support for Different OSes and Environments

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/oscal-cli#49]
# User Story:

An an OSCAL tools developer, in order to efficiently and quickly make use of this CLI tool, I would to have versioned `oscal-cli` releases packaged for different operating systems and environments for rapid use and operation.

We already have a community Docker package from usnistgov/oscal-cli#45, but this is around operating system package support for the `oscal-cli` as a separate kind of request, although related.

## Goals:

NOTE: This is an epic. Do you want to see support for a particular package manager? Please add a comment, work to add an issue for discussing or tracking the merge of code for adding building your package in the CI/CD. NIST OSCAL staff that are maintainers of this repo can work to update the list below to track linked issues in the epic for specific package manager requests.

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All website and readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by aj-stein-nist** [comment]
During today's Lunch with Devs call, @GaryGapinski is favorable to Linux package manager and finds them preferable to popular third-party macOS managers (e.g. `homebrew`, `port` from MacPorts). He recommended if possible, we find the optimal way to package the CLI for different Linux distributions with the most coverage (`.deb` for Ubuntu and Debian flavored Linux distros; `.rpm` for RedHat-flavored distros like RedHat, Fedora, CentOS, Amazon Linux, et cetera; potentially others).

Action-item from me: will add issues requesting `.deb` and `.rpm` generation separately, add tracker issues. If you are reading this and you want a different kind of Linux package manager package (like for OpenSuse or dare I say Arch Linux), you need to post to reply to this comment.

**Comment by aj-stein-nist** [comment]
Also, consider Chocolatey for Windows, per request from @Ikendiken in today's Lunch with Devs call.

Interested in other third-party package managers like `winget`? You need to reply to this comment separately and show interest!

**Comment by DavidAllardyce** [comment]
Yeah, Chocolatey and `winget` for Windows would be nice and, of course, NuGet is a must have for libs.

**Comment by xee5ch** [comment]
I would also enjoy [`asdf`](https://github.com/asdf-vm/asdf) if that is possible.

**Comment by xee5ch** [comment]
> I would also enjoy [`asdf`](https://github.com/asdf-vm/asdf) if that is possible.

An alpha version of the [`asdf` plugin for `oscal-cli` releases](https://github.com/xee5ch/asdf-oscal-cli) has been created by yours truly. Is there a desire @david-waltermire-nist to document these somewhere as it pertains to the repo here?
